name: CI - PR
on: [push, workflow_dispatch]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo OK
  DEV:
    runs-on: self-hosted
    needs: Build
    steps:
      - run: echo OK
  TEST:
    runs-on: self-hosted
    needs: DEV
    steps:
      - run: echo OK