name: Dev - Apply
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo OK
  DEV:
    runs-on: self-hosted
    steps:
      - run: echo OK
  TEST:
    runs-on: self-hosted
    steps:
      - run: echo OK
  DEV_DEPLOY:
    runs-on: self-hosted
    steps:
      - run: echo OK
  QA_DEPLOY:
    runs-on: self-hosted
    steps:
      - run: echo OK
  UAT_DEPLOY:
    runs-on: self-hosted
    steps:
      - run: echo OK
  PROD:
    runs-on: self-hosted
    steps:
      - run: echo OK